### ISSUE TITLE
unable to access "users/get_current_account"

### ISSUE THREAD

**Issue by Sahilberi** [dropbox/SwiftyDropbox#42] opened 2015-12-21 11:10 UTC
Hi,
   i'm following this  link https://www.dropbox.com/developers/documentation/swift#tutorial, but after authorized the client when i try to access data of user it returns nil. as it shows Bad Input: Error in call to API function "users/get_current_account": request body: could not decode input as JSON or
 Bad Input: Error in call to API function "files/list_folder": request body: could not decode input as JSON.

**Comment by varenc** [comment] 2015-12-22 23:36
hey there, could you share a little more information on how we might be able to reproduce that problem? make a link to a project you've setup that reproduces this?

**Comment by Sahilberi** [comment] 2015-12-23 06:07
hi @varenc , i just downloaded Swiftdropbox zip file and put it into my project(because of 'Swiftdropbox' not updated   for 'Alamofire'   3.1 and i'm using Alamofire 3.1).  i followed  this link https://blogs.dropbox.com/developers/2015/05/try-out-swiftydropbox-the-new-swift-sdk-for-dropbox-api-v2/  step by step.
but when i try to access  client.users.getCurrentAccount().response , it gives me nil
if let client = Dropbox.authorizedClient {

        // Get the current user's account info
        client.users.getCurrentAccount().response { response, error in
           print(response) //nil 
            print("*** Get current account ***")
            if let account = response {
                print("Hello \(account.name.givenName)!")
            } else {
                print(error!)
            }
        }

        // List folder
        client.files.listFolder(path: "").response { response, error in
            print("*** List folder ***")
            if let result = response {
                print("Folder contents:")
                for entry in result.entries {
                    print(entry.name)
                }
            } else {
                print(error!)
            }
        }

**Comment by smarx** [comment] 2015-12-23 06:12
If `response` is nil, then `error` should be non-nil. Was an error printed?

**Comment by Sahilberi** [comment] 2015-12-23 06:31
yes error printed . it shows Bad Input: Error in call to API function "users/get_current_account": request body: could not decode input as JSON.

**Comment by atomkirk** [comment] 2015-12-23 19:16
I am having the exact same problem when trying to access `files/list_folder`. Do something like this and you will be able to reproduce the problem:

```
        if let client = Dropbox.authorizedClient {
            StatusHUD.showLoadingWithCompletion {
                client.files.listFolder(path: self.path).response { response, error in
                    StatusHUD.dismissWithCompletion {
                        if let result = response {
                            self.entries = result.entries
                            self.tableView.reloadData()
                        } else {
                            self.showAlertWithTitle("Error", description: error?.description ?? "There was an unknown error.")
                        }
                    }
                }
            }
        }
```

**Comment by tylermann** [comment] 2015-12-23 21:52
I was having the same problems with the latest checkout. The issue seems to be caused by the following:
--- a/Pods/SwiftyDropbox/Source/Client.swift
+++ b/Pods/SwiftyDropbox/Source/Client.swift
```
-        
-        let request = client.manager.request(.POST, url, parameters: [:], headers: headers, encoding: ParameterEncoding.Custom {(convertible, _) in
+
+        let request = client.manager.request(.POST, url, parameters: ["something":"here"], headers: headers, encoding: ParameterEncoding.Custom {(convertible, _) in
                 let mutableRequest = convertible.URLRequest.copy() as! NSMutableURLRequest
                 mutableRequest.HTTPBody = dumpJSON(params)
                 return (mutableRequest, nil)
```

The block for the custom parameter encoding is not being run when an empty dictionary is passed in. If you add something to the parameters argument then the block is run. I'm guessing this probably used to work and broke in the recent Alamofire uprev to 3.0?

**Comment by atomkirk** [comment] 2015-12-23 22:13
That is the code I suspected as well but wasnt sure. Sure wish theyd expose the xproj and unit tests so we could help out ;)

**Comment by varenc** [comment] 2015-12-26 00:36
thanks for digging into this! Our office is mostly shutdown during the holidays but we should be able to get a fix out for this as soon as folks are back in the office.

The client aspect of these SDKs are actually automatically generated from a specification of the API.  This lets us ensure that all our SDKs of are always 100% up to date with the API, but it does complicate the SDK.  We plan to release the full code for the generators in the future, but we're not there yet.

**Comment by Sahilberi** [comment] 2015-12-28 07:08
thanks @tylermann . now it's working fine ,you were right it is happening bcz an empty dictionary is passed.

**Comment by marecektn** [comment] 2015-12-28 13:39
voting for fix :)

**Comment by leshkoapps** [comment] 2016-01-04 17:36
fixed in https://github.com/dropbox/SwiftyDropbox/pull/48

**Comment by varenc** [comment] 2016-01-06 02:35
I just accept #46 which should fix this.  (#48 fixes this too but 46 was first! :smile: )

**Closed** 2016-02-17 22:10 UTC
