### ISSUE TITLE
Update to Swift 2.0 Branch issuing error on call

### ISSUE THREAD

**Issue by fmaia** [dropbox/SwiftyDropbox#9] opened 2015-09-22 13:19 UTC
Hi!
I've been working on an app and testing the new v2 api for Swift. Everything was working fine... But when I updated to Xcode 7 and consequently started using the swift 2.0 branch I'm getting the following error:

Bad Input: Error in call to API function "users/get_current_account": Must provide HTTP header "Authorization" or URL parameter "authorization".

This is for the call in the following code:

func getAccountInfo() {
        
        if let client = Dropbox.authorizedClient {
            // Get the current user's account info
            client.usersGetCurrentAccount().response { response, error in
                if let account = response {
                    NSLog("Dropbox configured, hello \(account.name.givenName)")
                } else {
                    NSLog("Error in SCDropbox. \(error!.description)")
                    Dropbox.unlinkClient()
                }
            }
        } else {
            NSLog("Error in SCDropbox. There is no authorized client.")
        }
        
    }

Is there a solution for this? My app is configured for app level permissions only.
Thanks!

**Comment by biodave42** [comment] 2015-09-22 16:19
I _really, really_ hope you wonderful folks can get it together and prioritize shipping a production version of the v2 API with a Swift 2.0 SDK. You announced the beta way back in May. 

I too am using Xcode 7 and this Swift 2.0 branch and am confronted by this errror:

```
File didn't upload with error: Optional(Internal Server Error 502: <!DOCTYPE html>
<html>
<head><title>Dropbox - 5xx</title> 

[lots more HTML follows]

```
It's from the following code:
```
    func saveDataAsFileToDropBox(data:NSData, withFileName filePath:String) {
        
        if let client = Dropbox.authorizedClient {
            client.filesUpload(path: filePath, body: data).response { response, error in
                if let metadata = response {
                    print("Uploaded file: \(metadata.name)")
                } else {
                    print("File didn't upload with error: \(error)")
                }
            }
        } else {
            print("Whoops! Client not authorized")
        }
    }
```

**Comment by rpearl** [comment] 2015-09-28 21:08
I am not able to reproduce this issue. Something is causing the http stack / Alamofire to not provide the `Authorization` header but that should be done when the client is constructed.

Are there any more details you can give about how your app is set up?

**Comment by fmaia** [comment] 2015-09-29 13:29
It is nothing fancy. Most of the set up is pretty default. I am also using Pods for other libraries such as Realm. Currently, I reverted to the previous version of Xcode and SwiftyDropbox and it is working well. Could it be something related to the switch to Swift 2.0 and how Pods is linking stuff?

**Comment by s1gmund80** [comment] 2015-10-04 19:07
The same for me. 
I configured the project with pod as described in the db swifty tutorial, with SwiftyDropbox 0.4 and i'm almost able to link my dropbox account. But when i try to access to the user account to get the username i get the same error:

Bad Input: Error in call to API function "users/get_current_account": Must provide HTTP header "Authorization" or URL parameter "authorization".

I'm here to help if you need some more info

**Comment by smarx** [comment] 2015-10-04 19:30
@s1gmund80 Can you share code that reproduces this issue? Also, what do you mean by "almost able to link my dropbox account?" Have you linked your account or not at the time of this error?

**Comment by s1gmund80** [comment] 2015-10-04 20:33
I did few more tests. 
It seams that when i run the app from the simulator it considers me as already linked to dropbox account. I'm not sure if it is the standard behavior, but in this flow i've never explicitly linked the app to my DB account. So when i run this piece of code to check if the user is logged it enters in the **true** condition but raise the cited error.

// Verify user is logged into Dropbox
        if let client = Dropbox.authorizedClient {
            // Get the current user's account info
            client.usersGetCurrentAccount().response { response, error in
                if let account = response {
                    self.dropboxUsername.text="\(account.name.givenName)"
                } else {
                    print(error!)
                }
            }
            linkToDropboxButton.setTitle("Dropbox logout", forState: .Normal)
        }else{
            linkToDropboxButton.setTitle("link with Dropbox", forState: .Normal)
            dropboxUsername.text=""
        }

If I run the app from the device i'm able to link it to my dropbox account, and i'm able to retrieve my name without any warning/error. 
The only weird thing is that i have to hurry up to insert my mail address while linking to my account otherwise the webview change the login page.

**Comment by smarx** [comment] 2015-10-04 20:36
Have you tried resetting the simulator? Perhaps there's stale data there.

Could you explain what you mean when you say "i have to hurry up to insert my mail address while linking to my account otherwise the webview change the login page?" What does the page look like when you're entering your email address, and what does it look like after it "changes?"

**Comment by s1gmund80** [comment] 2015-10-05 20:44
On the iPhone as soon as the dropbox webview is opened it appears this screen. In less then a second the email field change color (it start with the same grey as the password field, then it turn to the lighter grey). 
![first_view](https://cloud.githubusercontent.com/assets/1709291/10292649/ace16dc4-6bb0-11e5-9b1a-4e2562ccad3c.png)
Here if you are not quick enough to tap in the email field and start to write something to take the focus (and i mean again in less then a second) it goes to the second screen, this one, intented for the forgot password flow: 
![second_view](https://cloud.githubusercontent.com/assets/1709291/10292655/b15722ea-6bb0-11e5-9753-d9cc50ab3e1d.png)

On the simulator i tried to reset contents and settings but the issue is still there. But i have some more info: when i run the app it consider the user as already linked, but it raise that errore trying accessing data. If i unlink the user and then i link a real one with the full procedure then i get no error accessing his data.
Furthermore, from that moment if i open the app without having the user linked it does not show the message anymore.
Doing a new reset it appears again until i explicit unlink this "fake" user and link again a real one.

Now it should be repeatable also to you. Let me know if you need some more info

ciao
i

**Comment by leah** [comment] 2015-10-06 19:51
Hi @s1gmund80,

It's really easy to accidentally click the "Did you forget your password?" link on the iOS simulator. Just be careful to click above the password box while testing. This isn't a problem on iOS devices so it's unlikely to be fixed any time soon.

If you experience any more issues, please reach out to us via our Developer Support: https://www.dropbox.com/developers/support

**Comment by fmaia** [comment] 2015-10-21 15:35
Hi! Just to let you know that I'm no longer able to reproduce the error above. I'm sorry that I can't track down what has changed... Thanks for the help anyway!

**Comment by rpearl** [comment] 2015-10-22 18:23
Thanks for the report in any case--if it comes up again, please open up a new task, hopefully we can track it down in a more principled way. Closing for now.

**Closed by rpearl** 2015-10-22 18:23 UTC

**Comment by rpearl** [comment] 2015-10-26 20:31
I believe there was an underlying issue in our keychain handling code which might have resulted in this error, which was fixed in fe07dab008642b174d1017de57c0a26c54672030.

**Comment by Dirk23** [comment] 2015-10-31 15:52
I followed the instructions here https://www.dropbox.com/developers/documentation/swift#tutorial for a simple test app, and always get the same error, like the threadstarter.

I simply do this:

    override func viewDidLoad() {
    super.viewDidLoad()
     title = NSLocalizedString("recepiesTableViewController", tableName: nil, bundle: NSBundle.mainBundle(), value: "brewhelper", comment: "NavigationBar Title")
     if Dropbox.authorizedClient == nil {
     print("Unauthorized")
            Dropbox.authorizeFromController(self)
        return
        } else {
            print("Authorized")
            dbUsername()
            listfolder()
        }
    func dbUsername() {
        if let client = Dropbox.authorizedClient {
            // Get the current user's account info
            client.usersGetCurrentAccount().response { response, error in
                print("*** Get current account ***")
                if let account = response {
                    print("Hello \(account.name.givenName)!")
                } else {
                    print(error!)
                }
            }
        } 
    }
    func listfolder () {
        if let client = Dropbox.authorizedClient {
            client.filesListFolder(path: "").response { response, error in
                print("*** List folder ***")
                if let result = response {
                    print("Folder contents:")
                    for entry in result.entries {
                        print(entry.name)
                    }
                } else {
                    print(error!)
                }
            }
        }
    }
    }

At the first start with a unlinked Client the Console says:

     -canOpenURL: failed for URL: "dbapi-2://1/connect" - error: "This app is not allowed to query for scheme dbapi-2"
     Presenting view controllers on detached view controllers is discouraged <brauhelfer.recepiesTableViewController: 0x7b6ecbb0>.
     Unbalanced calls to begin/end appearance transitions for <UINavigationController: 0x7c310a00>.

Then i log in and the Console says:

    Success! User is logged into Dropbox with token: xxxxxxxx

After restarting the App again, i seem to be Authorized, but i don't get the Username of the Account i'm logged in with and i can't list the Folder because:

     *** Get current account ***
     [request-id d7cc8138de7731765ccd6227079f655a] Bad Input: Error in call to API function "users/get_current_account": Must provide HTTP header "Authorization" or URL parameter "authorization".
     *** List folder ***
     [request-id 2a8067057125fdb143e5174c5d648ffa] Bad Input: Error in call to API function "files/list_folder": Must provide HTTP header "Authorization" or URL parameter "authorization".

What am i doing wrong here?

Regards

Dirk

**Comment by rpearl** [comment] 2015-10-31 19:27
Are you using release 0.6? If so there's still a bug here I need to track down. If you're on 0.5 or earlier, try upgrading to 0.6.

**Comment by Dirk23** [comment] 2015-11-01 09:46
i guess i use Tag 0.5, because i copy and pasted the Pod files contend from the  Readme with tag => '0.5'

I can see you updated the Readme to tag => '0.6'.
I changed my Podfile to tag 0.6 and ran pod update but the shell says:

     pod update
     Update all pods
     Updating local specs repositories
     Analyzing dependencies
     Pre-downloading: `SwiftyDropbox` from `git@github.com:dropbox/SwiftyDropbox.git`, tag `0.6`
     Downloading dependencies
     Using Alamofire (2.0.2)
     Installing SwiftyDropbox 0.5 (was 0.5)
     Generating Pods project
     Integrating client project
     Sending stats
     Pod installation complete! There is 1 dependency from the Podfile and 2 total pods installed.

so it is still 0.5?

How do i update on my side?

**Comment by rpearl** [comment] 2015-11-02 19:21
The "was 0.5" message was because I forgot to update the version field in the podspec. You should have the up-to-date code at this point. Sorry for the confusion here!

**Comment by varex33** [comment] 2015-11-14 19:50
Hi rpearl,

I have been getting problems linking dropbox to my app since I updated to swift 2 so I followed all the advice's here . In my last attempt, I updated my podfile with the tag 0.6 

Pre-downloading: `SwiftyDropbox` from `git@github.com:dropbox/SwiftyDropbox.git`, branch `swift-2.0`, tag `0.6`
Downloading dependencies
Using Alamofire (2.0.2)
Installing SwiftyDropbox 0.5 (was 0.2)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 2 total pods installed.\

However now when I try to link a user, I get the following error when the login window appears:
canOpenURL: failed for URL: "dbapi-2://1/connect" - error: "This app is not allowed to query for scheme dbapi-2"

And if I try to enter my credentials and login I get: 
LaunchServices: ERROR: There is no registered handler for URL scheme db-bd31o3eded5n334

I tried resetting my simulator, deleting my app from dropbox and creating a new one but nothing worked so got stuck here, any advice?
