### ISSUE TITLE
pod dependencies alamofire 3 (swift 2)

### ISSUE THREAD

**Issue by subinkk08** [dropbox/SwiftyDropbox#37] opened 2015-12-14 10:25 UTC
Hi,
I am working on swift 2.0 . i also using almofire 3.0  for my project . I want to add  swiftydropbox and when update pod  getting message like - `Alamofire (~> 2.0.2)` required by `SwiftyDropbox (2.0.0)`. what is the issue

**Comment by joeljfischer** [comment] 2015-12-14 20:03
The issue is that SwiftyDropbox is still stuck on Alamofire 2.0.2. This means that you'll have to stop using Alamofire 3.0 for your project and use 2.0.2 instead. I have the same issue.

**Comment by subinkk08** [comment] 2015-12-15 05:48
Thanks joeljfischer

**Comment by rpearl** [comment] 2015-12-17 23:48
Turns out we can just use Alamofire 3 here. Fixed in https://github.com/dropbox/SwiftyDropbox/commit/d5f2389961c760f1c8b77a5581c6bf794e778601.

**Closed by rpearl** 2015-12-17 23:48 UTC
