### ISSUE TITLE
Dropbox.authorizedClient is nil after successful login on macOS (10.13.5)

### ISSUE THREAD

**Issue by johnkountz** [dropbox/SwiftyDropbox#209] opened 2018-04-25 21:52 UTC
I recently started experiencing nil client response following call to DropboxClientsManager.authorizeFromController

This is on macOS

**Comment by greg-db** [comment] 2018-04-26 20:18
When you say you "recently started" seeing this, do you mean it was working without issue before with the same code? And if so, to the best of your knowledge, when did it start (e.g., was it with the update to 10.13.5)?

Additionally, the following would be helpful:
- the version(s) of Xcode you're seeing this with
- the relevant code snippets to reproduce the issue

Thanks in advance!

**Comment by johnkountz** [comment] 2018-04-27 00:05
Ok, 

I have more information on what appears to have changed in the Dropbox code.

I noticed that I am no longer getting an Apple Event following successful authentication. Perhaps you should try getting your macOS sample code working, I very much doubt it will as I coded my interface to match it. 

The sample code shows we are to make the following two calls in our initialization code:
            DropboxClientsManager.setupWithAppKeyDesktop("punccuwo71qw3ln")
            NSAppleEventManager.shared().setEventHandler(self, andSelector: #selector(handleGetURLEvent), forEventClass: AEEventClass(kInternetEventClass), andEventID: AEEventID(kAEGetURL))


What I noticed was that the event handler (handleGetURLEvent) was never being called.

I was able to work around this issue by making the following changes:

        DropboxClientsManager.authorizeFromController(sharedWorkspace: NSWorkspace.shared(),
                                                      controller: viewController,
                                                      openURL: { (url: URL) -> Void in

                                                        // *** THIS IS THE CHANGE I MADE, I simply called the following function with the result of the url parameter

                                                        if let authResult = DropboxClientsManager.handleRedirectURL(url) {
                                                            switch authResult {
                                                            case .success:
                                                                print("Success! User is logged into Dropbox.")
                                                                NotificationCenter.default.post(name: Notification.Name("db.auth"), object: nil, userInfo: nil);
                                                            case .cancel:
                                                                print("Authorization flow was manually canceled by user!")
                                                            case .error(_, let description):
                                                                print("Error: \(description)")
                                                            }
                                                        }

                                                        NSWorkspace.shared().open(url)
        })

**Comment by greg-db** [comment] 2018-04-27 15:46
Thanks! I'm glad you were able to get this working. We'll look into it.

**Comment by johnkountz** [comment] 2018-04-27 15:49
I am available to chat with whatever dev get’s assigned to this bug, feel free to email me if I can help verify the fix or help repo. the issue.

Cheers-

john kountz
Microsoft Software Engineer (Retired)
johnkountz@mac.com

**Comment by greg-db** [comment] 2018-05-02 16:16
I'm working on reproducing this, but it seems to be working properly for me. My `handleGetURLEvent` is getting called. I did have to make two small changes to the code from `https://github.com/dropbox/SwiftyDropbox#initialize-a-dropboxclient-instance` though:

Changes:
- `NSWorkspace.shared()` to `NSWorkspace.shared` (two instances)
- `func handleGetURLEvent` to `@objc func handleGetURLEvent`

The app wouldn't build without those changes. I believe these may be due to the version of Xcode/Swift though. I'll ask the team to update the documentation accordingly. 

For reference, I'm using:
- macOS 10.13.4
- Xcode 9.3
- Swift 4.1
- SwiftyDropbox 4.5.0

Can you let me know which versions you're using? You already mentioned the macOS version, but the rest would be useful.

Also, please let me know when this started occurring for you (e.g., was it with an update to macOS, Xcode, Swift, or SwiftyDropbox).

Thanks!

**Comment by johnkountz** [comment] 2018-05-03 16:47
macOS 10.13.5 (beta (17F59b))
xcode 9.3
Swift 3.2
current version of SwiftyDropbox

I can’t upgrade to Swift 4 as that would drop a number of my customers

Did you put a break-point on the handleGetURLEvent to verify it’s called?

I did, never gets called when i Link to Dropbox.

Thanks for the help.

-john

**Comment by johnkountz** [comment] 2018-05-04 13:38
Thank you for checking. I was able to work around this for now, perhaps i can isolate the code for an easy repo. That’s on me.

-john

**Comment by greg-db** [comment] 2018-06-01 18:09
One quick followup on this, I just tested this on 10.13.5 now, and it still works as expected for me, so it sounds like there's something else at play here.

**Comment by pangtuwi** [comment] 2018-08-21 21:41
Also getting a nil client as johnkountz.   Code originally worked as per github example (except for the two changes mentioned for Swift 4 which I also had to make).  Authenticated OK and then could access dropbox.   However stopped working later after I changed the Signing Team for the app.   (Changed this to try and stop the repeated requests for keychain password every time I ran the app).

Solution given by johnkountz does not work for me.  Still getting following error in log:


```
Success! User is logged into Dropbox. 

2018-08-21 23:35:33.935565+0200 FitForm[28531:2881543] dnssd_clientstub ConnectToServer: connect()-> No of tries: 1
2018-08-21 23:35:34.937060+0200 FitForm[28531:2881543] dnssd_clientstub ConnectToServer: connect()-> No of tries: 2
2018-08-21 23:35:35.942452+0200 FitForm[28531:2881543] dnssd_clientstub ConnectToServer: connect()-> No of tries: 3
2018-08-21 23:35:36.942657+0200 FitForm[28531:2881543] dnssd_clientstub ConnectToServer: connect() failed path:/var/run/mDNSResponder Socket:17 Err:-1 Errno:1 Operation not permitted
2018-08-21 23:35:36.942994+0200 FitForm[28531:2881543] [] nw_resolver_create_dns_service_locked DNSServiceCreateDelegateConnection failed: ServiceNotRunning(-65563)
2018-08-21 23:35:36.943555+0200 FitForm[28531:2881543] TIC TCP Conn Failed [1:0x600000179f80]: 10:-72000 Err(-65563)
2018-08-21 23:35:36.944281+0200 FitForm[28531:2881780] Task <BCFD5C8F-EC2D-4132-AC2E-D47FD4EFCC42>.<1> HTTP load failed (error code: -1003 [10:-72000])
2018-08-21 23:35:36.944444+0200 FitForm[28531:2880497] Task <BCFD5C8F-EC2D-4132-AC2E-D47FD4EFCC42>.<1> finished with error - code: -1003
DROPBOX Error: Error Domain=NSURLErrorDomain Code=-1003 "A server with the specified hostname could not be found." UserInfo={NSUnderlyingError=0x604001242a00 {Error Domain=kCFErrorDomainCFNetwork Code=-1003 "(null)" UserInfo={_kCFStreamErrorCodeKey=-72000, _kCFStreamErrorDomainKey=10}}, NSErrorFailingURLStringKey=https://api.dropbox.com/2/files/list_folder, NSErrorFailingURLKey=https://api.dropbox.com/2/files/list_folder, _kCFStreamErrorDomainKey=10, _kCFStreamErrorCodeKey=-72000, NSLocalizedDescription=A server with the specified hostname could not be found.}

```

**Comment by greg-db** [comment] 2018-08-22 14:50
@pangtuwi Are you sure you are getting `nil` client? From the output you shared, it looks like an API call is being attempted (which would require a client), but it failed because:
> A server with the specified hostname could not be found.

Based on that, and the rest of the output, that looks like a DNS failure when trying to resolve the 'api.dropbox.com' hostname for the Dropbox API servers. That's currently resolving properly for me though, so it sounds like there may be an issue with your network connection or DNS server.

**Comment by pangtuwi** [comment] 2018-08-22 15:48
I originally thought that was the case (DNS failure), but since
1. I can access the dropbox in a browser and 
2. the call to authoriseFromController is functioning
I dont think it is a DNS problem.

For clarity - the function that is working is 
`DropboxClientsManager.authorizeFromController(sharedWorkspace: NSWorkspace.shared,
                                                      controller: self,
                                                      openURL: { (url: URL) -> Void in
                                                        NSWorkspace.shared.open(url)
        })`
This redirects to the browser for authorisation.   If I confirm in the browser then it is returning success to the handleGetURLEvent in AppDelegate : 
` @objc func handleGetURLEvent(_ event: NSAppleEventDescriptor?, replyEvent: NSAppleEventDescriptor?) {
        if let aeEventDescriptor = event?.paramDescriptor(forKeyword: AEKeyword(keyDirectObject)) {
            if let urlStr = aeEventDescriptor.stringValue {
                let url = URL(string: urlStr)!
                if let authResult = DropboxClientsManager.handleRedirectURL(url) {
                    switch authResult {
                    case .success:
                        print("Success! User is logged into Dropbox. \n")
                    case .cancel:
                        print("Authorization flow was manually canceled by user!")
                    case .error(_, let description):
                        print("Error: \(description)")
                    }
                }
                // this brings your application back the foreground on redirect
                NSApp.activate(ignoringOtherApps: true)
            }
        }
    }`

Directly after I receive that confirmation - I trigger 
`    @IBAction func dropboxFileList(_ sender: Any) {
        self.filenames = []
        
        let client = DropboxClientsManager.authorizedClient
        _ = client?.files.listFolder(path: "/Apps/tapiriik").response { response, error in
            if let result = response {
                //print("Folder contents:")
                for entry in result.entries {
                    print(entry.name)
                    
                    if entry.name.hasSuffix(".tcx") || entry.name.hasSuffix(".fit") {
                        self.filenames?.append(entry.name)
                        self.dataTable.reloadData()
                    }
                }
            } else {
                print("DROPBOX Error: \(error!) \n")
            }
        }
    } //dropboxFileList`

If I put a break in the code and watch on the variable `client` after the line 
`let client = DropboxClientsManager.authorizedClient`
I see the following: 

`client	SwiftyDropbox.DropboxClient?	0x00006040001152a0
...
client.accessToken	String	"flHRF4ywQZAAAAAAAAAFbmlsX7YnUPHM1s-EMxOk6_Is0TFRatPaTpjTjjNw3JBh"	
client.selectUser	String?	nil	none`

The function then prints 
`DROPBOX Error: Error Domain=NSURLErrorDomain Code=-1003 "A server with the specified hostname could not be found." UserInfo={NSUnderlyingError=0x600000e53680 {Error Domain=kCFErrorDomainCFNetwork Code=-1003 "(null)" UserInfo={_kCFStreamErrorCodeKey=-72000, _kCFStreamErrorDomainKey=10}}, NSErrorFailingURLStringKey=https://api.dropbox.com/2/files/list_folder, NSErrorFailingURLKey=https://api.dropbox.com/2/files/list_folder, _kCFStreamErrorDomainKey=10, _kCFStreamErrorCodeKey=-72000, NSLocalizedDescription=A server with the specified hostname could not be found.} `

**Comment by greg-db** [comment] 2018-08-22 17:36
@pangtuwi Based on that output, it doesn't look like `client` is `nil` for you. (I see that `selectUser` is `nil`, but that's expected if you're not using that feature. The `client` itself appears to be there.)

Further, the Dropbox web site is served at www.dropbox.com (not api.dropbox.com), and the `authorizeFromController` method also does not use api.dropbox.com, so those working doesn't dispute the DNS error. (You would need a `client` to attempt to make the `list_folder` call anyway.)

That being the case, it does still seem to be a DNS issue on your network connection when trying to resolve api.dropbox.com. I recommend debugging why that might be (e.g., perhaps a proxy or firewall, etc., interfering, or just a malfunctioning DNS server). 

By the way, I redacted it from your post, but for the sake of security, you should disable that access token that you posted. You can do so by revoking access to the app entirely, if the access token is for your account, here:

https://www.dropbox.com/account/connected_apps

Or, you can disable just this access token using the API:

https://dropbox.github.io/dropbox-api-v2-explorer/#auth_token/revoke

**Comment by pangtuwi** [comment] 2018-08-22 22:02
@greg-db Appreciate your help - and the hint on the token.

I tried a ping to both www.dropbox.com and api.dropbox.com with success on both (replies from api.dropbox-dns.com and www.dropbox-dns.com , and also tried dig to both on the terminal, both times with success (I get 162.125.64.7 and 162.125.64.1 respectively - so my interpretation is that the DNS is ok.

**Comment by greg-db** [comment] 2018-08-23 15:58
@pangtuwi I took a closer look at the rest of the output you shared, and it seems to be identical to the error included in this thread:

https://forums.developer.apple.com/thread/67792#199442

Can you check if the same applies in your case? I.e., you may have a sandbox restriction preventing the DNS queries from succeeding.

**Comment by pangtuwi** [comment] 2018-08-23 20:51
That did it!  Turning off the App Sandbox solved the problem!  Will turn it back on and play with the settings.

**Closed** 2024-01-03 15:26 UTC
