### ISSUE TITLE
Once I unlink an account. Its never authorise any other account 

### ISSUE THREAD

**Issue by bhatti-waqas** [dropbox/SwiftyDropbox#184] opened 2017-09-14 11:10 UTC
Once I unlink any account from my app. using unlnkAllClient()
Then I am no longer be able to link authorise any other account. White blank screen appears and no error call back even.

**Comment by greg-db** [comment] 2017-09-14 15:26
@bhatti-waqas Can you elaborate on the issue you're running in to? Are you seeing a blank screen immediately upon calling `unlinkClients`, or is it only when calling `authorizeFromController` again? If it occurs when calling `authorizeFromController`, is it entirely blank, or is there some `SFSafariViewController` UI shown around it?

Any steps and code you can share to reproduce the issue would be helpful.

**Comment by bhatti-waqas** [comment] 2017-09-15 04:35
@greg-db : Thanks for your response 
I dont seed blank screen immediately upon calling unlinkClinets. Yes I see it when calling authorizeFromController again. and its entirely blank white screen. What I debugged is its looks like the SFSafariViewController keeps any session and doesn't load the drop box authentication again. 
Please refer the screenshot attached.

![simulator screen shot sep 14 2017 9 34 53 pm](https://user-images.githubusercontent.com/9653275/30466717-921535ca-9994-11e7-93dc-497637230c44.png)

**Comment by bhatti-waqas** [comment] 2017-09-15 04:36
Its causing alot of pain in coz user gets stuck in the app and can't do anything then. 
Your help would be much appreciated.

**Comment by greg-db** [comment] 2017-09-15 14:39
@bhatti-waqas I can't seem to reproduce this behavior. Can you share the steps and code for doing so? Thanks in advance!

**Comment by bhatti-waqas** [comment] 2017-09-19 05:40
@greg-db  yes sure. Let me share the code.
Here is flow of my app. When I logout from my app I use this line to unlink dropBox account


`DropboxClientsManager.unlinkClients()`

Then again when using app and try to upload something. I authorise again usin 

`DropboxClientsManager.authorizeFromController(UIApplication.shared,
                                                              controller: self,
                                                              openURL: { (url: URL) -> Void in
        
                                                                UIApplication.shared.open(url)
        })`

And it goes to white blank screen. as I attached above. What I debugged is something has to do with SFSFariViewContlroller's session management. 

Please your help will be much appreciated.

**Comment by greg-db** [comment] 2017-09-19 20:00
@bhatti-waqas Those pieces of code look right, and when using them I don't see this issue. Apologies for the bother, but that being the case, would you be able to provide a sample project that reproduces the issue?

Also, can you elaborate on what you mean when you say it "has to do with SFSFariViewContlroller's session management"? (In the screenshot, there isn't any `SFSafariViewController` visible. If there was and it was blank, I'd think this is a duplicate of #171.) Are you getting any error/output in the console?

**Comment by bhatti-waqas** [comment] 2017-09-20 05:40
@greg-db As I explained above. It goes back to blank screen.
There are two ways how I can produce this issue.

First 

1. connect drop boxy using code
`DropboxClientsManager.authorizeFromController(UIApplication.shared, controller: self, openURL: { (url: URL) -> Void in UIApplication.shared.open(url) })`

2. It will open SFFariViewController to authenticate.

3. Give some wrong credentials that account doesn't exist on dropBox. It will show error that password or username is incorrect. 

4. Again try to connect and it will take you to the blank screen.

Method #2

1. Unlink accounts using code 
`DropboxClientsManager.unlinkClients()
`
2. Authorise again using code

`DropboxClientsManager.authorizeFromController(UIApplication.shared, controller: self, openURL: { (url: URL) -> Void in UIApplication.shared.open(url) })`

It takes you to blank white screen. 
I will try to make a sample code and attach here.

**Comment by bhatti-waqas** [comment] 2017-09-20 10:09
Hi @greg-db : I think I have figured out the real case of reproducing the issue. Its pretty strange but if I call `DropboxClientsManager.authorizeFromController(UIApplication.shared, controller: self, openURL: { (url: URL) -> Void in UIApplication.shared.open(url) })` 
in viewDidlLoad() then It takes me to blank screen. If I make it wait for 1 second and then call it or call it on the action of any button then it works fine. Pretty much strange. And it happens second time I come in that controller.

**Comment by greg-db** [comment] 2017-09-20 17:57
> in viewDidlLoad() then It takes me to blank screen. If I make it wait for 1 second and then call it or call it on the action of any button then it works fine

Thanks! I'm glad to hear you got that working. I can't reproduce this using your other methods, but this one sort of reproduces the issue for me. By calling `authorizeFromController` in `viewDidLoad`, it sounds like the issue is just that you're effectively trying to present the `SFSafariViewController` before the load appeared. I just tried it, and it works if you call it in `viewDidAppear` instead of `viewDidLoad`.

**Closed by greg-db** 2017-09-20 17:57 UTC
