### ISSUE TITLE
Crash in NSDateSerializer.deserialize

### ISSUE THREAD

**Issue by sweetmandm** [dropbox/SwiftyDropbox#109] opened 2016-09-10 04:42 UTC
I've seen a crash report that I haven't been able to reproduce, and I'm wondering if anybody else has encountered this issue. I'm on SwiftyDropbox 3.2.0.

It appears to have happened after calling `upload(path:input:)`, when it was deserializing the json after an Alamofire completion.

Here's the stack trace. I suppose it must be hitting this fatalError if it's crashing in NSDateSerializer.deserialize?
https://github.com/dropbox/SwiftyDropbox/blob/master/Source/StoneSerializers.swift#L251

```
#0. Crashed: com.apple.main-thread
0  SwiftyDropbox                  0x5a9b90 _TTSf4g_n___TFC13SwiftyDropbox16NSDateSerializer11deserializefOS_4JSONCSo6NSDate + 260
1  SwiftyDropbox                  0x5a9b38 _TTSf4g_n___TFC13SwiftyDropbox16NSDateSerializer11deserializefOS_4JSONCSo6NSDate + 172
2  SwiftyDropbox                  0x5a4bd0 _TFC13SwiftyDropbox16NSDateSerializer11deserializefOS_4JSONCSo6NSDate + 68
3  SwiftyDropbox                  0x44f8c8 _TTSf4g_d___TFCC13SwiftyDropbox5Files22FileMetadataSerializer11deserializefOS_4JSONCS0_12FileMetadata + 848
4  SwiftyDropbox                  0x404d34 _TTWCC13SwiftyDropbox5Files22FileMetadataSerializerS_14JSONSerializerS_FS2_11deserializefOS_4JSONwx9ValueType + 184
5  SwiftyDropbox                  0x3f0624 _TFFC13SwiftyDropbox10RpcRequest8responseFFTGSqwx9ValueType_GSqGOS_9CallErrorw_S1____T_DGS0_xq__U_FTGSqCSo12NSURLRequest_GSqCSo17NSHTTPURLResponse_GSqCSo6NSData_GSqCSo7NSError__T_ + 520
6  SwiftyDropbox                  0x3eebe0 _TPA__TFFC13SwiftyDropbox13UploadRequest8responseFFTGSqwx9ValueType_GSqGOS_9CallErrorw_S1____T_DGS0_xq__U_FTGSqCSo12NSURLRequest_GSqCSo17NSHTTPURLResponse_GSqCSo6NSData_GSqCSo7NSError__T_ + 104
7  Alamofire                      0x2cb238 _TFFFC9Alamofire7Request8responseFT5queueGSqPSo17OS_dispatch_queue__17completionHandlerFTGSqCSo12NSURLRequest_GSqCSo17NSHTTPURLResponse_GSqCSo6NSData_GSqCSo7NSError__T__DS0_U_FT_T_U_FT_T_ + 200
8  libdispatch.dylib              0x20e77cbf _dispatch_call_block_and_release + 10
9  libdispatch.dylib              0x20e77cab _dispatch_client_callout + 22
10 libdispatch.dylib              0x20e7c559 _dispatch_main_queue_callback_4CF + 1532
11 CoreFoundation                 0x212a7755 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 8
12 CoreFoundation                 0x212a5c4f __CFRunLoopRun + 1590
13 CoreFoundation                 0x211f41c9 CFRunLoopRunSpecific + 516
14 CoreFoundation                 0x211f3fbd CFRunLoopRunInMode + 108
15 GraphicsServices               0x22810af9 GSEventRunModal + 160
16 UIKit                          0x25927435 UIApplicationMain + 144
17 record                         0xe52e0 main (AppDelegate.swift:15)
18 libdispatch.dylib              0x20ea0873 (Missing)
```

**Comment by greg-db** [comment] 2016-09-12 17:38
Thanks for the report! This looks like a duplicate of #47 . The fix for that is on master and will be included in the next release.

**Closed by greg-db** 2016-09-12 17:38 UTC
Labels: duplicate

**Comment by sweetmandm** [comment] 2016-09-12 17:40
Sorry about that, checked for dupes but missed it. Thanks!
