### ISSUE TITLE
SwiftDropbox is incompatible with iOS 4.2

### ISSUE THREAD

**Issue by danielsaidi** [dropbox/SwiftyDropbox#231] opened 2018-09-19 06:03 UTC
I get runtime errors for Alamofire after migrating an app of mine (that uses SwiftDropbox) to Swift 4.2.

```
dyld: Symbol not found: _$S8Dispatch0A3QoSV0B6SClassO7utilityyA2EmFWC
  Referenced from: /Users/admin/Library/Developer/CoreSimulator/Devices/69F0BD96-7BB8-4B29-BE96-A423BA2FBD3C/data/Containers/Bundle/Application/CAAB9A58-4F89-4C85-BCDA-8ECF22D11731/VandelayExample.app/Frameworks/Alamofire.framework/Alamofire
  Expected in: /Users/admin/Library/Developer/CoreSimulator/Devices/69F0BD96-7BB8-4B29-BE96-A423BA2FBD3C/data/Containers/Bundle/Application/CAAB9A58-4F89-4C85-BCDA-8ECF22D11731/VandelayExample.app/Frameworks/libswiftDispatch.dylib
 in /Users/admin/Library/Developer/CoreSimulator/Devices/69F0BD96-7BB8-4B29-BE96-A423BA2FBD3C/data/Containers/Bundle/Application/CAAB9A58-4F89-4C85-BCDA-8ECF22D11731/VandelayExample.app/Frameworks/Alamofire.framework/Alamofire
(lldb) 
```

I think the underlying error is that SwiftyDropbox uses `Alamofire 4.5`. Bumping the dependency to the latest `4.7.x` version could perhaps solve this problem.

**Comment by gereons** [comment] 2018-09-29 08:46
FYI, this is a dupe of #204 which has been ignored for >8 months now.

**Comment by danielsaidi** [comment] 2018-09-30 16:43
Yeah, I noticed that. Until they approve any of the PRs or fix it themselves, I have to add the latest Alamofire version to my library.

**Comment by danielsaidi** [comment] 2018-10-01 05:13
I just noticed that although `SwiftyDropbox` can be imported into an app using the Cartfile maneuver above, I can not push new versions of a pod of mine that depends on `SwiftyDropbox`, because the pod linting process fails.

**Comment by gereons** [comment] 2018-10-01 08:54
Feel free to use my fork at https://github.com/gereons/SwiftyDropbox which has just this change.

**Comment by danielsaidi** [comment] 2018-10-02 21:35
I have created a VandelayDropbox bug that describes this problem: https://github.com/danielsaidi/VandelayDropbox/issues/1

**Comment by greg-db** [comment] 2018-10-03 15:05
@danielsaidi Thanks for the detailed information! I'll share this with the team.

**Comment by surkis** [comment] 2018-10-04 13:48
Sent pull request: https://github.com/dropbox/SwiftyDropbox/pull/233 with support swift 4.2 for iOS. Please review and merge it if you want.
For now I am using this way: 
`pod 'SwiftyDropbox', :git => 'https://github.com/surkis/SwiftyDropbox'`

**Comment by danielsaidi** [comment] 2018-10-04 14:09
Cool, but this does not work with podspec dependencies.

**Comment by surkis** [comment] 2018-10-04 14:50
@danielsaidi, could you please explain what did you mean?
I have integration in my iOS project and it’s working well.

**Comment by danielsaidi** [comment] 2018-10-04 19:31
The format you specified works in a `Podfile` file but it does not (or have I missed something fundamental) work in a `.podspec` file dependency list.

**Comment by greg-db** [comment] 2018-11-07 21:16
The podspec and Cartfile have been updated for Alamofire 4.7 in the latest release of the SwiftyDropbox SDK.

**Closed by greg-db** 2018-11-07 21:16 UTC

**Comment by danielsaidi** [comment] 2018-11-11 09:47
Hi @greg-db  

This is still not fully resolved. Sure, I can now remove the additional `Alamofire` line in my `Cartfile` and `podspec` and Xcode manages to build the project, but my pod can still not be linted, since `SwiftyDropbox` is still not migrated to Swift 4.2. This gives me the following lint error:

```
 -> VandelayDropbox (0.7.2)
...
    - ERROR | [iOS] xcodebuild:  SwiftyDropbox/Source/SwiftyDropbox/Platform/SwiftyDropbox_iOS/OAuthMobile.swift:169:29: error: 'UIAlertControllerStyle' has been renamed to 'UIAlertController.Style'
...

[!] The spec did not pass validation, due to 3 errors and 3 warnings.
```

**Comment by greg-db** [comment] 2018-11-12 15:36
@danielsaidi Thanks for the note. We have #237 open for that. Please follow that for updates.
