### ISSUE TITLE
Crash at DropboxTransportClient: 707 when downloading empty file (zero bytes)

### ISSUE THREAD

**Issue by KennethFra** [dropbox/SwiftyDropbox#352] opened 2022-01-24 17:32 UTC
This forced unwrap crashes as response.data is nil.  It only happens when the file being downloaded has zero bytes.
In my case it was a .txt file with zero bytes.
It also crashed here when a file was marked as ".txt" and it actually contained PDF data for the same reason.

`completionHandler((resultObject, response.data!), nil)
`
SwiftyDropbox 8.2.1
AlamoFire 5.5.0
iOS Simulator iPad Pro, iOS 15.2

**Comment by greg-db** [comment] 2022-01-24 18:23
Thanks for the report. This appears to be a duplicate of #344 so I'll close this in favor of that one. Please subscribe to that for updates.

**Closed by greg-db** 2022-01-24 18:23 UTC

**Comment by greg-db** [comment] 2022-04-15 13:31
This is now fixed in v8.3.0.
